baseurl = "/"
title = "Vinoth babu blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Vinoth Babu"
    description = "My Rants"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2022"

[Permalinks]
    post = "/:filename/"

[deployment]

[[deployment.targets]]
name = "Vinoth Babu"
URL = "s3://vinothbabu.com"

cloudFrontDistributionID = "E2BVR245D7NGP3"

[[deployment.matchers]]
# Cache static assets for 20 years.
pattern = "^.+\\.(js|css|svg|ttf|woff|woff2|eot|png|jpg|gif|svg|ttf)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
